<a href="https://colab.research.google.com/github/HariKeerthana-13/AIMLProjectLab/blob/main/AIML/IIIThyd/IHUB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Sample user features (Mx1 vector) - let's say 2 features
user_features = np.array([[0.8],    # e.g., interest in sports
                          [0.4]])   # e.g., interest in tech

# Sample product features (1xN vector) - let's say 3 features
product_features = np.array([[1.0, 0.5, 0.2]])  # e.g., price level, popularity, category match

# Outer product to compute interaction matrix
interaction_matrix = np.dot(user_features, product_features)

# Display results
print("User Features (Mx1):")
print(user_features)
print("\nProduct Features (1xN):")
print(product_features)
print("\nInteraction Matrix (MxN):")
print(interaction_matrix)


User Features (Mx1):
[[0.8]
 [0.4]]

Product Features (1xN):
[[1.  0.5 0.2]]

Interaction Matrix (MxN):
[[0.8  0.4  0.16]
 [0.4  0.2  0.08]]
